security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        chain_provider:
            chain:
                providers: [app_patient_provider, app_praticien_provider]
        app_patient_provider:
            entity:
                class: App\Entity\Patient
                property: email
        app_praticien_provider:
            entity:
                class: App\Entity\Praticien
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            provider: chain_provider
            guard:
                authenticators:
                    - App\Security\UserAuthentificatorAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }